name: run tests
description: run tests based on jest, fast-check, nestjs/testing
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Install skaffold
      shell: bash
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        sudo install skaffold /usr/local/bin/
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
    - name: install bun package manager
      run: npm i -g bun
      shell: bash
    - run: bun i
      shell: bash
    - run: npm test
      shell: bash
    - run: bun i -g wait-on
      shell: bash
    - run: nohup npm run start:dev &
      shell: bash
      continue-on-error: true
    - name: Check nest server port opens
      shell: bash
      run: |
        npx wait-on http://localhost:3000/api/swagger && \
        sudo kill -9 `sudo lsof -t -i:3000`
    - name: Run skaffold
      shell: bash
      run: |
        skaffold config set --global collect-metrics false && \
        skaffold build && \
        skaffold run
    - name: Wait until app & db running
      shell: bash
      run: |
        kubectl wait sts/nestjs-fast-check-practice-database --for condition=Running && \
        kubectl wait deploy/nestjs-fast-check-practice --for condition=Running
    - name: Run kubectl exec test
      shell: bash
      run: |
        kubectl exec -it deploy/nestjs-fast-check-practice -- /bin/bash -c ". /root/.nvm/nvm.sh && npm run test"
