apiVersion: v1
kind: Service
metadata:
  name: {{ include "nestjs-fast-check-practice.fullname" . }}-database
  labels:
    {{- include "nestjs-fast-check-practice.database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: database
      protocol: TCP
      name: database
  selector:
    {{- include "nestjs-fast-check-practice.database.selectorLabels" . | nindent 4 }}
