name: CD
on:
  push:
  pull_request:

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ghcr.io/dps0340/nestjs-fast-check-practice:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          cache: true
