name: CD
on:
  push:
  pull_request:

jobs:
  nest-test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ghcr.io/DPS0340/nestjs-fast-check-practice
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
