name: run tests & build and push container image
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/ci
  build-and-push-container-image:
    runs-on: ubuntu-24.04
    needs:
      - tests
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: nestjs-fast-check-practice
          tag: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          cache: true
