name: CI
on:
  push:
  pull_request:

jobs:
  nest-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: corepack install -g yarn@4.2.2
      - run: corepack yarn set version 4.2.2 # for persistence, use 'yarn policies set-version 4.2.2'
      - run: corepack yarn
      - run: yarn test
      - run: npm i -g wait-on
      - run: nohup yarn start:dev &
        continue-on-error: true
      - name: Check nest server port opens
        run: |
          npx wait-on http://localhost:3000/api/swagger && \
          sudo kill -9 `sudo lsof -t -i:3000`
