name: CI
on:
  push:
  pull_request:

jobs:
  nest-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install bun package manager
        run: |
          curl -fsSL https://bun.sh/install | bash && \
          export PATH="~/.bun/bin/bun:$PATH"
      - run: bun i
      - run: bun test
      - run: bun i -g wait-on
      - run: nohup bun start:dev &
        continue-on-error: true
      - name: Check nest server port opens
        run: |
          npx wait-on http://localhost:3000/api/swagger && \
          sudo kill -9 `sudo lsof -t -i:3000`
